Fixed java.lang.NoSuchMethodError caused by mixed dependencies of jersey 1 and 2
This is only a fast workaround. Switching to exclusevly one of the versions was not possible and should be attempted accross all samply components